CREATE TABLE country(
    idcountry INTEGER NOT NULL PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL
);

CREATE TABLE city(
    idcity INTEGER NOT NULL PRIMARY KEY,
    nombre_city VARCHAR(30) NOT NULL
);

CREATE TABLE contiene(
    idContiene INTEGER PRIMARY KEY,
    countryId INTEGER FOREIGN KEY REFERENCES country(idcountry) ON DELETE CASCADE ON UPDATE SET NULL,
    cityId INTEGER FOREIGN KEY REFERENCES city(idcity) ON DELETE CASCADE ON UPDATE SET NULL 
);